AWSTemplateFormatVersion: 2010-09-09

Resources:
      
  primerLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: hadellambdafunction
      Runtime: python3.9
      Role: !GetAtt RootRole.Arn
      Handler: index.handler
      Code:
        ZipFile: |
          import json
          import boto3
          var aws = require('aws-sdk')
          var response = require('cfn-response')
          exports.handler = function(event, context) {
              s3 = boto3.resource('s3')
            
            sourcebucketName = event['Records'][0]['s3']['bucket']['name']
            destinationbucket = 'hadelbucket4'
            objectkey = event['Records'][0]['s3']['object']['key']
            copy_source = {
                'Bucket': sourcebucketName,
                'Key': objectkey
            }
            s3.meta.client.copy(copy_source, destinationbucket, objectkey)
            
            return {
                'statusCode': 200,
                'body': json.dumps('Hello from Lambda!')
            }
          }


  S3Bucket1:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: hadelbucket3
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:Put'
          - Function: 'arn:aws:lambda:us-east-1:437652894623:function:hadellambdafunction'

  S3Bucket2:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: hadelbucket4

  RootRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: 
              Service: 
                - "lambda.amazonaws.com"
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Action:
              - s3:*
              - s3-object-lambda:*
              Resource: "*"
            - Effect: Allow
              Action:
                - 'logs:CreateLogGroup'
                - 'logs:CreateLogStream'
                - 'logs:PutLogEvents'
              Resource: '*'


